expand close button on global header.
gem-tanzanite/gem-tanzanite.github.io pull request #22
Opened 2016-11-09 05:52 UTC by sassy

closeボタンが押しにくいのでさらにおおきくした。

2016-11-09 07:15 UTC, aKosukeNagano commented
おぉ、良くなった。

2016-11-09 08:09 UTC, aKosukeNagano commented
上に少々ズレているのが気になるので修正お願いします。 @sassy

2016-11-10 00:42 UTC, sassy commented
@aKosukeNagano  ボタンの位置調整しました。

2016-11-10 01:39 UTC, ghost requested changes

2016-11-10 01:39 UTC, aKosukeNagano commented on scss/style.scss
>  		height: 50px;
こいつを7px分縮めてもらえますか。インスペクタでみたときにヘッダ部分からはみ出てしまっており、意図しない動作に繋がる恐れがあります。

2016-11-10 02:28 UTC, sassy reviewed
修正しました。

2016-11-10 07:03 UTC, sassy commented
mergeできなくなっていたので、rebase.

2016-11-11 01:18 UTC, sassy commented
@aKosukeNagano 修正がOKならばapproveお願いします。

2016-11-11 01:21 UTC, ghost approved these changes

2016-11-11 01:21 UTC, merged

2016-11-11 01:21 UTC, ghost commented
approved.